### ISSUE TITLE
How to add the "Add Link" thorough TFS API  

### ISSUE THREAD

**Issue by devandqatools** [ashamrai/TFRestApi#1]
Hi Ashamrai,

Could you please provide the how to add the link in my existing work item, that means how to add link type "parent"

Regards 
Chidvilash

**Comment by ashamrai** [comment]
The source json request is described here: [Add a link](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/update?view=azure-devops-rest-5.1#add-a-link).

I`ve added to my custom example [07.TFRestApiAppWorkItemLinks](https://github.com/ashamrai/TFRestApi/tree/master/07.TFRestApiAppWorkItemLinks) new function [AddParentLink](https://github.com/ashamrai/TFRestApi/blob/034ed3b4a009c0097d4951cb423c7171669a1b14/07.TFRestApiAppWorkItemLinks/TFRestApiApp/Program.cs#L210). This code adds new parent link:

```
WorkItem parentWi = WitClient.GetWorkItemAsync(ParentWiId).Result; // get parent to retrieve its url

Dictionary<string, object> fields = new Dictionary<string, object>();

fields.Add(RelConstants.LinkKeyForDict + RelConstants.ParentRefStr + parentWi.Id, // to use as unique key
CreateNewLinkObject(RelConstants.ParentRefStr, parentWi.Url, "Parent " + parentWi.Id));

return SubmitWorkItem(fields, WiId);

```

**Comment by devandqatools** [comment]
Hey thank you, Do you have same API in Java?

**Comment by ashamrai** [comment]
No, I do not have, However, I think it is not very complex task to work with Rest Api through java, Here is my simple example to get work item: [AzureDevOpsRestApiJavaExample](https://github.com/ashamrai/AzureDevOpsExtensions/tree/master/AzureDevOpsRestApiJavaExample)
