### ISSUE TITLE
by using System.Parent we are get the parent work item id but how we get the child workitem id

### ISSUE THREAD

**Issue by devandqatools** [ashamrai/TFRestApi#2]

**Comment by ashamrai** [comment]
The rest api does not return ids of childs, you can find example here: [Get list of work items, all expanded](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/list?view=azure-devops-rest-5.1#get-list-of-work-items,-all-expanded).
To get child ids:

1. Call `GetWorkItemAsync` with `expand: WorkItemExpand.Relations` for a parent work item. Example: [GetWorkItemWithRelations](https://github.com/ashamrai/TFRestApi/blob/034ed3b4a009c0097d4951cb423c7171669a1b14/02.TFRestApiAppGetWorkItems/TFRestApiApp/Program.cs#L93)

2. Check links in the result and find links with `Rel == System.LinkTypes.Hierarchy-Forward`. Then you can extract ID from the url: [ExtractWiIdFromUrl](https://github.com/ashamrai/TFRestApi/blob/034ed3b4a009c0097d4951cb423c7171669a1b14/02.TFRestApiAppGetWorkItems/TFRestApiApp/Program.cs#L144)
