### ISSUE TITLE
is there any way to update the created date field?

### ISSUE THREAD

**Issue by devandqatools** [ashamrai/TFRestApi#3]
Is there a way to update the created date field using ADO API’s. and Can we clone the bugs through automation? While “cloning”?
Does the created date field set to current\latest date?
Does the attachments will be carried over to the new\cloned work item?

Could you please suggest

**Comment by ashamrai** [comment]
You can find some explanation here: [Update Work Item PATCH System.CreatedDate with bypassRules](https://developercommunity.visualstudio.com/content/problem/412569/update-work-item-patch-systemcreateddate-with-bypa.html). We can set a custom value to the 
 _System.CreatedDate_ filed on the creation step only with the _bypassRules_ parameter.
To clone a work item, we can just copy fields of a source work item to a new one and add bypassRules:

`WorkItem clonedWi = witClient.CreateWorkItemAsync(patchDocument, teamProjectName, wiType, bypassRules: true).Result;`

Here you can find simple example to clone work item without system filed: https://github.com/ashamrai/AzureDevOpsExtensions/tree/master/CustomNetTasks/CloneWorkItem

I did not try to clone attachments yes, I`ll try it soon.
