### ISSUE TITLE
How to Remove existing values in System.Tag

### ISSUE THREAD

**Issue by devandqatools** [ashamrai/TFRestApi#4]
Hi Ashamrai,

How to remove Previous all values in  'System.Tag'.

**Comment by ashamrai** [comment]
Can you explain your problem? Do you want to remove some old tags from Azure DevOps team project or from work item? You can find some basic info about tags here: [Delete, remove, or manage tags](https://docs.microsoft.com/en-us/azure/devops/boards/queries/add-tags-to-work-items?view=azure-devops#delete-remove-or-manage-tags).

> You can't delete a tag itself. However, if you delete a tag from all work items to which it's currently assigned, the system will delete the tag. The system automatically deletes unassigned tags after 3 days of disuse.

**Comment by devandqatools** [comment]
Hi Ashamrai,
![image](https://user-images.githubusercontent.com/43774814/79971449-f30cc680-84b1-11ea-90f4-0b3c5a6a7db2.png) How do we remove work item type bug tags through API

**Comment by ashamrai** [comment]
You should update **System.Tags** field (not System.Tag) with empty string:

```
                Dictionary<string, object> fields = new Dictionary<string, object>();

                fields.Add("System.Tags", "");

                UpdateWorkItem(our_id, fields);

        static WorkItem UpdateWorkItem(int WIId, Dictionary<string, object> Fields)
        {
            JsonPatchDocument patchDocument = new JsonPatchDocument();

            foreach (var key in Fields.Keys)
                patchDocument.Add(new JsonPatchOperation()
                {
                    Operation = Operation.Add,
                    Path = "/fields/" + key,
                    Value = Fields[key]
                });

            return WitClient.UpdateWorkItemAsync(patchDocument, WIId).Result;
        }
```
