### ISSUE TITLE
Java Code for Tfs api connection and get the work items

### ISSUE THREAD

**Issue by devandqatools** [ashamrai/TFRestApi#7]
Hi Ashamrai, 
Thank you for your quick response. How to connect tfs api and get the work items in java code. 
Thanks,
Chidvilash

**Comment by ashamrai** [comment]
You can find a small example here https://github.com/ashamrai/AzureDevOpsExtensions/blob/master/AzureDevOpsRestApiJavaExample/src/com/restapi/sample/ResApiMain.java
